# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseUsernameWithPulsing.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QByteArray, Qt, QSize
from PyQt5.QtGui import QMovie
from PyQt5.QtWidgets import QSizePolicy, QLabel, QVBoxLayout


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 242)
        Dialog.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftPane = QtWidgets.QFrame(Dialog)
        self.LeftPane.setMinimumSize(QtCore.QSize(185, 0))
        self.LeftPane.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LeftPane.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.LeftPane.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftPane.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LeftPane.setLineWidth(0)
        self.LeftPane.setObjectName("LeftPane")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LeftPane)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.ShowGif = QtWidgets.QLabel(self.LeftPane)
        self.ShowGif.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ShowGif.setText("")
        self.ShowGif.setScaledContents(True)
        self.ShowGif.setObjectName("ShowGif")

        ##Show Gif Movie
        self.movie = QMovie(":/Pulsing/PulsingGradiant.gif", QByteArray(), self.LeftPane)
        self.ShowGif.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.ShowGif.setAlignment(Qt.AlignCenter)
        self.movie.setCacheMode(QMovie.CacheAll)
        self.ShowGif.setMovie(self.movie)
        self.movie.start()
        self.movie.loopCount()

        # setting layout
        self.ShowGifLayout = QVBoxLayout(self.ShowGif)
        self.ShowGifLayout.setSpacing(6)
        self.ShowGifLayout.setContentsMargins(0, 50, 0, 90)

        self.UserIcon = QLabel(self.ShowGif)
        self.UserIcon.setMaximumSize(QSize(200, 200))
        self.UserIcon.setPixmap(QtGui.QPixmap(":/Pulsing/UserIcon.png"))
        self.UserIcon.setScaledContents(True)
        self.UserIcon.setStyleSheet(u"QLabel {\n"
                                    "background-color:none;\n"
                                    "}\n"
                                    "")
        self.ShowGifLayout.addWidget(self.UserIcon)

        self.UserName = QLabel("Username", self.ShowGif)
        self.UserName.setAlignment(Qt.AlignHCenter)
        self.UserName.setStyleSheet(u"QLabel {\n"
                                    "color: white;\n"
                                    "font: 12pt \"MS Shell Dlg 2\";\n"
                                    "border-top:none;\n"
                                    "border-left:none;\n"
                                    "border-right:none;\n"
                                    "border-bottom: none;\n"
                                    "background-color:none;\n"
                                    "}\n"
                                    "")

        self.ShowGifLayout.addWidget(self.UserName)

        self.horizontalLayout_2.addWidget(self.ShowGif)
        self.horizontalLayout.addWidget(self.LeftPane)
        self.RightPane = QtWidgets.QFrame(Dialog)
        self.RightPane.setStyleSheet(u"\n"
                                     "border:none;\n"
                                     "background-image: url(:/Pulsing/BG_Username.png);\n"
                                     "")
        self.RightPane.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightPane.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightPane.setObjectName("RightPane")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RightPane)
        self.verticalLayout.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.RightPane)
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setStyleSheet(u"QLineEdit {\n"
                                    "color: white;\n"
                                    "font: 12pt \"MS Shell Dlg 2\";\n"
                                    "border-top:none;\n"
                                    "border-left:none;\n"
                                    "border-right:none;\n"
                                    "border-bottom: 1px solid silver;\n"
                                    "border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, "
                                    "stop:0.00568182 rgba(17, 241, 155, 225), stop:0.892045 rgba(9, 72, 54, 255));\n "
                                    "background:transparent;\n"
                                    "}\n"
                                    "")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setFrame(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        # Connect Line Edit to Label
        self.lineEdit.textChanged.connect(self.UserName.setText)
        self.verticalLayout.addWidget(self.lineEdit)
        self.SaveDetails = QtWidgets.QPushButton(self.RightPane)
        self.SaveDetails.setStyleSheet("QPushButton {\n"
                                       "        font-size: 12pt;\n"
                                       "        color: silver;\n"
                                       "        background-color: #333;\n"
                                       "        padding-top: 5px;\n"
                                       "        padding-bottom: 5px;\n"
                                       "          border-radius: 5px;\n"
                                       "        border: none\n"
                                       "    }\n"
                                       "    \n"
                                       "    QPushButton:hover {\n"
                                       "        background-color: rgba(255, 255, 255, 30);\n"
                                       "        /*border-radius: 5px;*/\n"
                                       "        color: white;\n"
                                       "    }\n"
                                       "    \n"
                                       "    QPushButton:pressed {\n"
                                       "        background-color: transparent;\n"
                                       "        border: 1px solid #777;\n"
                                       "        border-radius: 5px;\n"
                                       "    }")
        self.SaveDetails.setCheckable(False)
        self.SaveDetails.setChecked(False)
        self.SaveDetails.setDefault(False)
        self.SaveDetails.setFlat(False)
        self.SaveDetails.setObjectName("SaveDetails")
        self.verticalLayout.addWidget(self.SaveDetails)
        self.horizontalLayout.addWidget(self.RightPane)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.setGeometry(0, 0, 548, 200)
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Enter Username"))
        self.SaveDetails.setText(_translate("Dialog", "Confirm"))

import Client.Username.PulsingGradient_rc

